import test from 'node:test';
import assert from 'node:assert/strict';
import {
  PROFILE_CONTEXT,
  resetProfileContextForTests,
  resolveProfileContext,
  scopedStorageKey,
  validProfileKey
} from '../assets/profile-context.js';

test('legacy local owner keeps the original database and storage keys', () => {
  const context = resolveProfileContext();
  assert.equal(context.cryptographicallyVerified, false);
  assert.equal(context.databaseName, 'sakthiai-owner-platform');
  assert.equal(context.storagePrefix, '');
  assert.equal(context.legacyCompatible, true);
  assert.equal(scopedStorageKey(context, 'sakthiai-active-project'), 'sakthiai-active-project');
});

test('verified identity receives a deterministic isolated database namespace', () => {
  const context = resolveProfileContext({
    identity: {
      authenticated: true,
      cryptographicallyVerified: true,
      profileKey: 'profile-0123456789abcdef01234567',
      role: 'member',
      maskedEmail: 'me***@example.com',
      assurance: 'cloudflare-access-jwt-rs256-verified'
    }
  });
  assert.equal(context.cryptographicallyVerified, true);
  assert.equal(context.profileKey, 'profile-0123456789abcdef01234567');
  assert.equal(context.databaseName, 'sakthiai-owner-platform-profile-0123456789abcdef01234567');
  assert.equal(context.storagePrefix, 'sakthiai:profile-0123456789abcdef01234567:');
  assert.equal(context.role, 'member');
  assert.equal(context.crossDeviceSyncEnabled, false);
  assert.equal(context.serverPersistenceEnabled, false);
  assert.equal(
    scopedStorageKey(context, 'sakthiai-owner-lock-v1'),
    'sakthiai:profile-0123456789abcdef01234567:sakthiai-owner-lock-v1'
  );
});

test('unverified or malformed profile keys fall back to the existing owner database', () => {
  for (const profileKey of ['', 'profile-short', 'profile-../../escape', 'owner@example.com']) {
    const context = resolveProfileContext({
      identity: { authenticated: true, cryptographicallyVerified: true, profileKey, role: 'owner' }
    });
    assert.equal(context.databaseName, PROFILE_CONTEXT.legacyDatabaseName);
    assert.equal(context.cryptographicallyVerified, false);
  }
});

test('profile keys accept only the pseudonymous format generated by the Worker', () => {
  assert.equal(validProfileKey('profile-0123456789abcdef01234567'), true);
  assert.equal(validProfileKey('PROFILE-0123456789ABCDEF01234567'), false);
  assert.equal(validProfileKey('profile-0123456789abcdef0123456789'), false);
});

test('scoped storage keys require a non-empty logical key', () => {
  assert.throws(() => scopedStorageKey(resolveProfileContext(), ''), /storage key/i);
});

test('test cache reset remains available for deterministic browser-context tests', () => {
  assert.doesNotThrow(() => resetProfileContextForTests());
});
