import test from 'node:test';
import assert from 'node:assert/strict';
import { buildAuditEnvelope } from '../src/runtime-v4/audit.js';
import { ownerBoundary, state } from '../src/runtime-v4/core.js';
import { validateClassification, validateExport, validateRetention } from '../src/runtime-v4/governance.js';
import { validateMembership } from '../src/runtime-v4/membership.js';
import { validateRole } from '../src/runtime-v4/roles.js';
import { validateSharing } from '../src/runtime-v4/sharing.js';
import { trustSnapshot, validateAccessibility } from '../src/runtime-v4/trust.js';
import { validateWorkspace } from '../src/runtime-v4/workspace.js';
import { handleRuntimeWave4, RUNTIME_WAVE_4_RELEASE } from '../src/runtime-wave4.js';

const headers = { 'cf-access-authenticated-user-email': 'owner@example.com', 'cf-access-jwt-assertion': 'verified' };
const enabled = { OWNER_EMAIL: 'owner@example.com', RUNTIME_WAVE4_ENABLED: 'true', RUNTIME_WAVE4_EMERGENCY_STOP: 'false' };
const request = (url, init = {}) => new Request(url, { ...init, headers: { ...headers, ...(init.headers || {}) } });

test('release stable', () => assert.equal(RUNTIME_WAVE_4_RELEASE, 'runtime-wave-4.0.0'));
test('defaults safe', () => { const s = state({}); assert.equal(s.enabled, false); assert.equal(s.emergencyStopped, true); assert.equal(s.operational, false); });
test('operational needs both flags', () => assert.equal(state(enabled).operational, true));
test('owner boundary needs JWT', () => assert.equal(ownerBoundary(new Request('https://x', { headers: { 'cf-access-authenticated-user-email': 'owner@example.com' } }), enabled).allowed, false));
test('workspace proposal valid and non-persistent', () => { const r = validateWorkspace({ name: 'Hub', slug: 'owner-hub', region: 'uk', dataZone: 'private' }); assert.equal(r.valid, true); assert.equal(r.proposal.createWorkspace, false); });
test('public workspace denied', () => assert.equal(validateWorkspace({ name: 'Hub', slug: 'owner-hub', region: 'uk', dataZone: 'private', public: true }).valid, false));
test('membership valid but no invite', () => { const r = validateMembership({ email: 'reviewer@example.com', role: 'reviewer', justification: 'Review' }); assert.equal(r.valid, true); assert.equal(r.proposal.invitationSent, false); });
test('invite sending denied', () => assert.equal(validateMembership({ email: 'x@y.com', role: 'viewer', justification: 'x', sendInvitation: true }).valid, false));
test('role allowlist works', () => assert.equal(validateRole({ roleId: 'reviewer', permissions: ['workspace.read', 'evidence.review'] }).valid, true));
test('write permission rejected', () => assert.equal(validateRole({ roleId: 'bad', permissions: ['workspace.write'] }).valid, false));
test('private sharing valid but no link', () => { const r = validateSharing({ resourceId: 'r1', resourceType: 'document', audience: 'named-reviewers' }); assert.equal(r.valid, true); assert.equal(r.proposal.linkCreated, false); });
test('public link denied', () => assert.equal(validateSharing({ resourceId: 'r1', resourceType: 'document', audience: 'owner-only', publicLink: true }).valid, false));
test('credentials need restricted classification', () => assert.equal(validateClassification({ level: 'internal', categories: ['credentials'] }).valid, false));
test('restricted credentials valid', () => assert.equal(validateClassification({ level: 'restricted', categories: ['credentials'] }).valid, true));
test('metadata export valid but not generated', () => { const r = validateExport({ format: 'json', scope: 'audit-metadata', reason: 'Owner review' }); assert.equal(r.valid, true); assert.equal(r.request.exportGenerated, false); });
test('content export denied', () => assert.equal(validateExport({ format: 'json', scope: 'audit-metadata', reason: 'x', includeContent: true }).valid, false));
test('retention valid but not applied', () => { const r = validateRetention({ recordType: 'audit-metadata', days: 365 }); assert.equal(r.valid, true); assert.equal(r.policy.applied, false); });
test('immediate deletion denied', () => assert.equal(validateRetention({ recordType: 'audit-metadata', days: 365, deleteNow: true }).valid, false));
test('audit envelope hashes subject and logs no content', async () => { const r = await buildAuditEnvelope({ eventType: 'workspace.proposed', subjectId: 'subject-1', purpose: 'Review' }); assert.equal(r.valid, true); assert.equal(r.envelope.contentLogged, false); assert.equal(r.envelope.subjectFingerprint.length, 20); });
test('unknown audit event rejected', async () => assert.equal((await buildAuditEnvelope({ eventType: 'shell.run', subjectId: 'x', purpose: 'x' })).valid, false));
test('accessibility profile valid without certification claim', () => { const r = validateAccessibility({ language: 'ta', requirements: ['keyboard', 'screen-reader'] }); assert.equal(r.valid, true); assert.equal(r.profile.wcagCertificationClaim, false); });
test('trust snapshot has no certification claims', () => { const r = trustSnapshot(); assert.equal(r.claims.certified, false); assert.equal(r.workspaceWrites, false); });
test('status endpoint safe while disabled', async () => { const response = await handleRuntimeWave4(new Request('https://x/api/v1/runtime/v4/status'), {}, new URL('https://x/api/v1/runtime/v4/status')); assert.equal(response.status, 200); assert.equal((await response.json()).operational, false); });
test('private route requires Access', async () => { const response = await handleRuntimeWave4(new Request('https://x/api/v1/runtime/v4/trust-centre'), enabled, new URL('https://x/api/v1/runtime/v4/trust-centre')); assert.equal(response.status, 401); });
test('disabled route blocked', async () => { const r = request('https://x/api/v1/runtime/v4/trust-centre'); const response = await handleRuntimeWave4(r, { OWNER_EMAIL: 'owner@example.com' }, new URL(r.url)); assert.equal(response.status, 503); });
test('emergency stop blocks route', async () => { const r = request('https://x/api/v1/runtime/v4/trust-centre'); const response = await handleRuntimeWave4(r, { OWNER_EMAIL: 'owner@example.com', RUNTIME_WAVE4_ENABLED: 'true' }, new URL(r.url)); assert.equal((await response.json()).code, 'RUNTIME_WAVE_4_EMERGENCY_STOPPED'); });
test('owner can validate proposal when operational', async () => { const r = request('https://x/api/v1/runtime/v4/workspaces/validate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: 'Hub', slug: 'owner-hub', region: 'uk', dataZone: 'private' }) }); const response = await handleRuntimeWave4(r, enabled, new URL(r.url)); assert.equal(response.status, 200); assert.equal((await response.json()).result.proposal.createWorkspace, false); });
test('owner can view trust posture when operational', async () => { const r = request('https://x/api/v1/runtime/v4/trust-centre'); const response = await handleRuntimeWave4(r, enabled, new URL(r.url)); assert.equal(response.status, 200); assert.equal((await response.json()).snapshot.claims.productionReady, false); });
