import test from 'node:test';
import assert from 'node:assert/strict';
import { validateAlertPolicy } from '../src/runtime-v5/alerting.js';
import { evaluateBurnRate } from '../src/runtime-v5/burn-rate.js';
import { evaluateChangeRisk } from '../src/runtime-v5/change-risk.js';
import { ownerBoundary, runtimeState } from '../src/runtime-v5/core.js';
import { buildRollbackPlan, evaluateDeploymentGate } from '../src/runtime-v5/deployment.js';
import { buildSreEvidencePacket } from '../src/runtime-v5/evidence.js';
import { aggregateHealth } from '../src/runtime-v5/health.js';
import { triageIncident } from '../src/runtime-v5/incident.js';
import { selectRunbook } from '../src/runtime-v5/runbook.js';
import { evaluateSlo, validateSlo } from '../src/runtime-v5/slo.js';
import { sanitizeTelemetry } from '../src/runtime-v5/telemetry.js';
import { handleRuntimeWave5, RUNTIME_WAVE_5_RELEASE } from '../src/runtime-wave5.js';

const headers = { 'cf-access-authenticated-user-email': 'owner@example.com', 'cf-access-jwt-assertion': 'verified' };
const enabled = { OWNER_EMAIL: 'owner@example.com', RUNTIME_WAVE5_ENABLED: 'true', RUNTIME_WAVE5_EMERGENCY_STOP: 'false' };
const request = (url, init = {}) => new Request(url, { ...init, headers: { ...headers, ...(init.headers || {}) } });

test('release stable', () => assert.equal(RUNTIME_WAVE_5_RELEASE, 'runtime-wave-5.0.0'));
test('defaults disabled and emergency stopped', () => { const s = runtimeState({}); assert.equal(s.enabled, false); assert.equal(s.emergencyStopped, true); assert.equal(s.operational, false); });
test('operational needs enable and stop release', () => assert.equal(runtimeState(enabled).operational, true));
test('no production or paid actions in state', () => { const s = runtimeState(enabled); assert.equal(s.productionWritesEnabled, false); assert.equal(s.paidMonitoringEnabled, false); assert.equal(s.deploymentsExecuted, false); });
test('owner boundary requires Access JWT', () => assert.equal(ownerBoundary(new Request('https://x', { headers: { 'cf-access-authenticated-user-email': 'owner@example.com' } }), enabled).allowed, false));
test('SLO definition valid', () => assert.equal(validateSlo({ service: 'sakthiai', indicator: 'availability', targetPercent: 99.9, windowDays: 30 }).valid, true));
test('SLO indicator allowlist enforced', () => assert.equal(validateSlo({ service: 'x', indicator: 'cost', windowDays: 30 }).valid, false));
test('latency threshold only for latency', () => assert.equal(validateSlo({ service: 'x', indicator: 'availability', windowDays: 30, thresholdMs: 500 }).valid, false));
test('SLO evaluation target met', () => { const r = evaluateSlo({ totalEvents: 100000, goodEvents: 99950, targetPercent: 99.9 }); assert.equal(r.valid, true); assert.equal(r.evaluation.targetMet, true); assert.equal(r.evaluation.alertSent, false); });
test('SLO requires positive events', () => assert.equal(evaluateSlo({ totalEvents: 0, goodEvents: 0 }).valid, false));
test('burn rate critical classification', () => assert.equal(evaluateBurnRate({ targetPercent: 99.9, shortWindowErrorRatePercent: 2, longWindowErrorRatePercent: 1 }).evaluation.severity, 'critical'));
test('burn rate never sends alert', () => assert.equal(evaluateBurnRate({ targetPercent: 99.9, shortWindowErrorRatePercent: 5, longWindowErrorRatePercent: 5 }).evaluation.alertSent, false));
test('SEV1 for data integrity risk', () => assert.equal(triageIncident({ title: 'Integrity risk', dataIntegrityRisk: true }).triage.severity, 'SEV1'));
test('incident is not created', () => assert.equal(triageIncident({ title: 'Latency', affectedUsersPercent: 10 }).triage.incidentCreated, false));
test('change risk high without controls', () => { const r = evaluateChangeRisk({ changeId: 'c1', scope: 'database', dataMigration: true, rollbackTested: false, automatedTestsPassed: false }); assert.equal(r.evaluation.risk, 'critical'); assert.equal(r.evaluation.changeExecuted, false); });
test('low-risk documentation change', () => assert.equal(evaluateChangeRisk({ changeId: 'c2', scope: 'documentation', rollbackTested: true, automatedTestsPassed: true }).evaluation.risk, 'low'));
test('deployment gate eligible only with evidence', () => { const r = evaluateDeploymentGate({ releaseId: 'r1', testsPassed: true, securityValidationPassed: true, rollbackPlanVerified: true, errorBudgetRemainingPercent: 50 }); assert.equal(r.valid, true); assert.equal(r.gate.decision, 'eligible-for-human-approval'); assert.equal(r.gate.deploymentExecuted, false); });
test('deployment blocked by writes request', () => assert.equal(evaluateDeploymentGate({ releaseId: 'r1', testsPassed: true, securityValidationPassed: true, rollbackPlanVerified: true, errorBudgetRemainingPercent: 50, productionWritesRequested: true }).valid, false));
test('rollback plan does not execute', () => { const r = buildRollbackPlan({ releaseId: 'r1', previousVersion: 'v1', reason: 'Regression' }); assert.equal(r.valid, true); assert.equal(r.plan.rollbackExecuted, false); assert.equal(r.plan.commandsGenerated, false); });
test('runbook allowlist selection', () => assert.equal(selectRunbook({ symptom: 'worker-5xx' }).valid, true));
test('unknown runbook denied', () => assert.equal(selectRunbook({ symptom: 'delete-database' }).valid, false));
test('health aggregate detects unavailable', () => assert.equal(aggregateHealth({ components: [{ name: 'api', status: 'healthy' }, { name: 'auth', status: 'unavailable' }] }).aggregate.overall, 'unavailable'));
test('health aggregate performs no probe', () => assert.equal(aggregateHealth({ components: [{ name: 'api', status: 'healthy' }] }).aggregate.externalProbeExecuted, false));
test('dashboard-only alert policy valid', () => assert.equal(validateAlertPolicy({ name: 'SLO', condition: 'slo-breach', destination: 'dashboard-only' }).valid, true));
test('external webhook denied', () => assert.equal(validateAlertPolicy({ name: 'SLO', condition: 'slo-breach', destination: 'dashboard-only', webhookUrl: 'https://example.com' }).valid, false));
test('alert sending denied', () => assert.equal(validateAlertPolicy({ name: 'SLO', condition: 'slo-breach', destination: 'dashboard-only', sendNow: true }).valid, false));
test('telemetry redacts credentials and email', async () => { const r = await sanitizeTelemetry({ eventType: 'error', service: 'api', message: 'api_key=secret user@example.com' }); assert.equal(r.valid, true); assert.match(r.telemetry.message, /REDACTED/); assert.match(r.telemetry.message, /EMAIL_REDACTED/); assert.equal(r.telemetry.rawContentPersisted, false); });
test('evidence packet fingerprints rationale', async () => { const r = await buildSreEvidencePacket({ releaseId: 'r1', decision: 'block', rationale: 'Error budget exhausted', checks: ['tests'] }); assert.equal(r.valid, true); assert.equal(r.packet.rationaleFingerprint.length, 24); assert.equal(r.packet.persisted, false); });
test('invalid evidence decision rejected', async () => assert.equal((await buildSreEvidencePacket({ releaseId: 'r1', decision: 'deploy-now', rationale: 'x' })).valid, false));
test('public status safe while disabled', async () => { const response = await handleRuntimeWave5(new Request('https://x/api/v1/runtime/v5/status'), {}, new URL('https://x/api/v1/runtime/v5/status')); const body = await response.json(); assert.equal(response.status, 200); assert.equal(body.operational, false); assert.equal(body.alertsSent, false); });
test('private route requires Access', async () => { const response = await handleRuntimeWave5(new Request('https://x/api/v1/runtime/v5/slo/validate', { method: 'POST', body: '{}' }), enabled, new URL('https://x/api/v1/runtime/v5/slo/validate')); assert.equal(response.status, 401); });
test('disabled runtime blocks private route', async () => { const r = request('https://x/api/v1/runtime/v5/slo/validate', { method: 'POST', body: '{}' }); const response = await handleRuntimeWave5(r, { OWNER_EMAIL: 'owner@example.com' }, new URL(r.url)); assert.equal((await response.json()).code, 'RUNTIME_WAVE_5_DISABLED'); });
test('emergency stop blocks private route', async () => { const r = request('https://x/api/v1/runtime/v5/slo/validate', { method: 'POST', body: '{}' }); const response = await handleRuntimeWave5(r, { OWNER_EMAIL: 'owner@example.com', RUNTIME_WAVE5_ENABLED: 'true' }, new URL(r.url)); assert.equal((await response.json()).code, 'RUNTIME_WAVE_5_EMERGENCY_STOPPED'); });
test('operational owner can evaluate SLO without side effects', async () => { const r = request('https://x/api/v1/runtime/v5/slo/evaluate', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ totalEvents: 1000, goodEvents: 999, targetPercent: 99.9 }) }); const response = await handleRuntimeWave5(r, enabled, new URL(r.url)); const body = await response.json(); assert.equal(response.status, 200); assert.equal(body.result.evaluation.alertSent, false); });
